pipeline:
    name: test1243
    identifier: test1243
    projectIdentifier: CI_Demos_new_gitX
    orgIdentifier: default
    tags: {}
    stages:
        - stage:
              name: test
              identifier: test
              type: CI
              spec:
                  cloneCodebase: false
                  infrastructure:
                      type: KubernetesDirect
                      spec:
                          connectorRef: account.test123
                          namespace: gfhgf
                          automountServiceAccountToken: true
                          nodeSelector: {}
                          os: Linux
                  execution:
                      steps:
                          - step:
                                type: Run
                                name: echo
                                identifier: echo
                                spec:
                                    connectorRef: account.nofar_dockerhub
                                    image: alpine
                                    shell: Sh
                                    command: echo sdsd
